version: '3.5'

services:

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '8910:80'
    environment:
      - NODE_ENV=production